#!/bin/sh
# Script to see if anything updated on the google servers.
# If so a new release should be build.
# Intented to be run via cron.

rm -rf old.pool
cp -r {,old.}pool
make sitemap slowmirror pool
diff -r {,old.}pool
