#!/bin/sh
# Script to see if anything updated on the google servers.
# If so a new release should be build.
# Intented to be run via cron.

set -e

make sitemap > /dev/null 2>&1
diff sitemap.mirrored sitemap
