#!/bin/sh
# Script to see if anything updated on the google servers.
# If so a new release should be build.
# Intented to be run via cron.

rm -rf new.pool/
POOLDIR=./new.pool ./update_pool > /dev/null

diff -r pool/ new.pool/
