#!/usr/bin/env perl
## Ah, c'mon. I never get to use Perl anymore nowadays!
#
# Loads all obvious URLS from google's library listing.
#
# Use as:
# curl -s https://developers.google.com/speed/libraries/devguide | this.thing > urls
#
use strict;
use warnings;
local $/ = undef;
my $html = <>;

my %libs;

# The page isn't valid XML, so some simple regexes to find the libraries will do.
while ($html =~ m|<dl>(.*?)</dl>|sg) {
    my $lib = $1;
    my ($title) = ($lib =~ m|<dt>(.*?)</dt>|);
    next if not $title;
    #print("$title\n");
    #
    $libs{$title} = [];

    my ($baseurl) = ($lib =~ m|src="//(ajax.googleapis.com/ajax/libs/.*?)"|);
    $baseurl =~ s|\d[\d.]+|XXXX|; # version number changes in the base url.
    #print("$baseurl\n");
    while ($lib =~ m|<span class="versions">(.*?)</span>|sg) {
        for my $version (split /,/, $1) {
            $version =~ s/\s//g;
            #print(" $title: -$version\n");
            my $url = $baseurl;
            $url =~ s/XXXX/$version/;
            print("$url\n");
            push $libs{$title}, $version;
        }
    }
}

## Special cases.
# CSS for jQuery Mobile
for my $v (@{$libs{"jQuery Mobile"}}) {
    ## TODO: there are image files linked in the stylesheet
    print("ajax.googleapis.com/ajax/libs/jquerymobile/$v/jquery.mobile.min.css\n");
}
# jQuerty themes
# ... and all the images they need :/
#

# script.aculo.us might load more files.
for my $v (@{$libs{"script.aculo.us"}}) {
    print <<HERE
ajax.googleapis.com/ajax/libs/scriptaculous/$v/builder.js
ajax.googleapis.com/ajax/libs/scriptaculous/$v/controls.js
ajax.googleapis.com/ajax/libs/scriptaculous/$v/dragdrop.js
ajax.googleapis.com/ajax/libs/scriptaculous/$v/effects.js
ajax.googleapis.com/ajax/libs/scriptaculous/$v/slider.js
ajax.googleapis.com/ajax/libs/scriptaculous/$v/sound.js
HERE
}
